databases:
  - name: taskflow-db
    plan: free
    region: ohio
    postgresMajorVersion: 16

services:
  - type: web
    name: taskflow
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromService:
          type: postgresql
          name: taskflow-db
          property: connectionString
