databases:
  - name: taskflow-db
    plan: free
    region: ohio
    postgresMajorVersion: 16

services:
  - type: web
    name: taskflow
    runtime: docker
    region: ohio
    plan: free
    branch: main
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgresql
          name: taskflow-db
          property: connectionString
